### PR TITLE
Updates pull-request reviewers

### PR DESCRIPTION
**Pull request by baz8080**
### Changes

Brendan messaged me
"Remove me please", he did ask
Task completed, bye!

### Reviewers
@brendan-fahy @baz8080 @schlan @eepDev

### References
- None

### Risks
- None

### CODE REVIEW

**Comment by schlan** [comment]
I think I disagree, we should always tag @brendan-fahy

**Comment by schlan** [comment]
@brendan-fahy

**Comment by bridgeri127** [comment]
@schlan, @brendan-fahy has indicated that he does not wish to be tagged on these PRs. Therefore please refrain from tagging @brendan-fahy . @brendan-fahy has a right to be left in peace.

**Comment by baz8080** [comment]
haha, I told brendan you would want to re-add him if we removed him, prophecy confirmed!

**Comment by baz8080** [comment]
@brendan-fahy would be good to get your eyes on this PR. Thanks!

**Pull request merged**
